version: "3"
services:
  beautysaloon_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: beautysaloon

  beautysaloon:
    image: dikobra3/beautysaloon:v1.0
    environment:
      WAIT_HOSTS: beautysaloon_db:3306
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - beautysaloon_db
